package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Actors generated by hbm2java
 */
public class Actors  implements java.io.Serializable {


     private Integer id;
     private String gender;
     private String firstName;
     private String lastName;
     private String details;
     private Set movieCasts = new HashSet(0);

    public Actors() {
    }

    public Actors(String gender, String firstName, String lastName, String details, Set movieCasts) {
       this.gender = gender;
       this.firstName = firstName;
       this.lastName = lastName;
       this.details = details;
       this.movieCasts = movieCasts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set getMovieCasts() {
        return this.movieCasts;
    }
    
    public void setMovieCasts(Set movieCasts) {
        this.movieCasts = movieCasts;
    }




}


