package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CustomersRentals generated by hbm2java
 */
public class CustomersRentals  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private TransactionTypes transactionTypes;
     private Rentals rentals;
     private Accounts accounts;
     private Date date;
     private Integer amount;
     private String comment;

    public CustomersRentals() {
    }

    public CustomersRentals(Users users, TransactionTypes transactionTypes, Rentals rentals, Accounts accounts, Date date, Integer amount, String comment) {
       this.users = users;
       this.transactionTypes = transactionTypes;
       this.rentals = rentals;
       this.accounts = accounts;
       this.date = date;
       this.amount = amount;
       this.comment = comment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public TransactionTypes getTransactionTypes() {
        return this.transactionTypes;
    }
    
    public void setTransactionTypes(TransactionTypes transactionTypes) {
        this.transactionTypes = transactionTypes;
    }
    public Rentals getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Rentals rentals) {
        this.rentals = rentals;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


