package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private Integer id;
     private Date dateRegisterd;
     private String memberNumber;
     private String fullName;
     private String gender;
     private String phone;
     private String email;
     private String address;
     private String details;
     private Set accountses = new HashSet(0);
     private Set rentalses = new HashSet(0);

    public Customers() {
    }

    public Customers(Date dateRegisterd, String memberNumber, String fullName, String gender, String phone, String email, String address, String details, Set accountses, Set rentalses) {
       this.dateRegisterd = dateRegisterd;
       this.memberNumber = memberNumber;
       this.fullName = fullName;
       this.gender = gender;
       this.phone = phone;
       this.email = email;
       this.address = address;
       this.details = details;
       this.accountses = accountses;
       this.rentalses = rentalses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDateRegisterd() {
        return this.dateRegisterd;
    }
    
    public void setDateRegisterd(Date dateRegisterd) {
        this.dateRegisterd = new Date();
    }
    public String getMemberNumber() {
        return this.memberNumber;
    }
    
    public void setMemberNumber(String memberNumber) {
        this.memberNumber = memberNumber;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set getAccountses() {
        return this.accountses;
    }
    
    public void setAccountses(Set accountses) {
        this.accountses = accountses;
    }
    public Set getRentalses() {
        return this.rentalses;
    }
    
    public void setRentalses(Set rentalses) {
        this.rentalses = rentalses;
    }




}


