package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Formats generated by hbm2java
 */
public class Formats  implements java.io.Serializable {


     private Integer id;
     private String details;
     private Set movieses = new HashSet(0);

    public Formats() {
    }

    public Formats(String details, Set movieses) {
       this.details = details;
       this.movieses = movieses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Set getMovieses() {
        return this.movieses;
    }
    
    public void setMovieses(Set movieses) {
        this.movieses = movieses;
    }




}


