package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0



/**
 * MovieCast generated by hbm2java
 */
public class MovieCast  implements java.io.Serializable {


     private Integer id;
     private Movies movies;
     private Actors actors;

    public MovieCast() {
    }

    public MovieCast(Movies movies, Actors actors) {
       this.movies = movies;
       this.actors = actors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }
    public Actors getActors() {
        return this.actors;
    }
    
    public void setActors(Actors actors) {
        this.actors = actors;
    }




}


