package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * Movies generated by hbm2java
 */
public class Movies implements java.io.Serializable {

    private Integer id;
    private Formats formats;
    private Stores stores;
    private Genres genres;
    private Integer releaseYear;
    private String title;
    private String description;
    private Integer stock;
    private String rentalOrSale;
    private Integer rentalDailyRate;
    private Integer price;
    private Set movieCasts = new HashSet(0);
    private Set rentalses = new HashSet(0);

    public Movies() {
    }

    public Movies(Formats formats, Stores stores, Genres genres, Integer releaseYear, String title, String description, Integer stock, String rentalOrSale, Integer rentalDailyRate, Integer price, Set movieCasts, Set rentalses) {
        this.formats = formats;
        this.stores = stores;
        this.genres = genres;
        this.releaseYear = releaseYear;
        this.title = title;
        this.description = description;
        this.stock = stock;
        this.rentalOrSale = rentalOrSale;
        this.rentalDailyRate = rentalDailyRate;
        this.price = price;
        this.movieCasts = movieCasts;
        this.rentalses = rentalses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Formats getFormats() {
        return this.formats;
    }

    public void setFormats(Formats formats) {
        this.formats = formats;
    }

    public Stores getStores() {
        return this.stores;
    }

    public void setStores(Stores stores) {
        this.stores = stores;
    }

    public Genres getGenres() {
        return this.genres;
    }

    public void setGenres(Genres genres) {
        this.genres = genres;
    }

    public Integer getReleaseYear() {
        return this.releaseYear;
    }

    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getStock() {
        return this.stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public String getRentalOrSale() {
        return this.rentalOrSale;
    }

    public void setRentalOrSale(String rentalOrSale) {
        this.rentalOrSale = rentalOrSale;
    }

    public Integer getRentalDailyRate() {
        return this.rentalDailyRate;
    }

    public void setRentalDailyRate(Integer rentalDailyRate) {
        this.rentalDailyRate = rentalDailyRate;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Set getMovieCasts() {
        return this.movieCasts;
    }

    public void setMovieCasts(Set movieCasts) {
        this.movieCasts = movieCasts;
    }

    public Set getRentalses() {
        return this.rentalses;
    }

    public void setRentalses(Set rentalses) {
        this.rentalses = rentalses;
    }

}
