package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private Integer id;
     private String descriptions;
     private Set accountses = new HashSet(0);

    public Payments() {
    }

    public Payments(String descriptions, Set accountses) {
       this.descriptions = descriptions;
       this.accountses = accountses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Set getAccountses() {
        return this.accountses;
    }
    
    public void setAccountses(Set accountses) {
        this.accountses = accountses;
    }




}


