package vemo.model.entity;
// Generated Sep 28, 2015 1:49:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rentals generated by hbm2java
 */
public class Rentals  implements java.io.Serializable {


     private Integer id;
     private Customers customers;
     private Movies movies;
     private Integer status;
     private Date dateOut;
     private Date dateReturned;
     private Integer amount;
     private Set customersRentalses = new HashSet(0);

    public Rentals() {
    }

    public Rentals(Customers customers, Movies movies, Integer status, Date dateOut, Date dateReturned, Integer amount, Set customersRentalses) {
       this.customers = customers;
       this.movies = movies;
       this.status = status;
       this.dateOut = dateOut;
       this.dateReturned = dateReturned;
       this.amount = amount;
       this.customersRentalses = customersRentalses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Movies getMovies() {
        return this.movies;
    }
    
    public void setMovies(Movies movies) {
        this.movies = movies;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getDateOut() {
        return this.dateOut;
    }
    
    public void setDateOut(Date dateOut) {
        this.dateOut = dateOut;
    }
    public Date getDateReturned() {
        return this.dateReturned;
    }
    
    public void setDateReturned(Date dateReturned) {
        this.dateReturned = dateReturned;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Set getCustomersRentalses() {
        return this.customersRentalses;
    }
    
    public void setCustomersRentalses(Set customersRentalses) {
        this.customersRentalses = customersRentalses;
    }




}


